### ISSUE TITLE
Couldnt infer pool/dataset

### ISSUE THREAD

**Issue by drobban** [illuria/jailer#13]
When running jailer with a system with multiple pools jailer is unable assume a default path for the jails.

In that case we have the option to tell the command which one we would like to use.

What I also think could be useful, is if we are able to supply a default - In my case im just repeating a default everytime Im calling jailer and would be more helpful to give an argument when default is no longer whished or when a default in config isnt available.

Give a shout if this is something I can help out with implementing.

peace out =) and thx for the awesome util!

**Comment by antranigv** [comment]
This is very helpful and would be very easy to implement. we would have a `-Z otherpool/otherdataset`, and it will do the `zfs recv` to that, while reading the Jail bootstrap from `zdefault/jaildataset`. does that sound reasonable?

**Comment by antranigv** [comment]
Hey @drobban ! can you check out https://github.com/illuria/jailer/commit/d4ccf4c65cb03ec3833638cfd3b2a5172fd2a388 and test it? I think I've fixed the issue with multi-zpool deployments! looks like the details were in `jailer-init(8)`, and thanks to @kfv that manual has been there for a long time! :D 

Thank you for using FreeBSD, Jails, and illuria's Jailer!

**Comment by drobban** [comment]
Hi @antranigv!

I have now tested it out and it seems to behave as I would expect it =)
